Refactoring itemlist
jun34724/LeftMyTime pull request #2
Opened 2021-07-15 07:33 UTC by jun34724

각 변수명 규칙 변경(camelCase), recyclerview 아이템을 지정하는 객체 itemlist.class -> AdapterItem.class 로 이름 변경,
각 아이템 항목의 내용 받아오는 (시간이 지나간 percentage) 함수 interface 생성. 각 객체 생성.

개선이 필요한 내용:
mainactivity의 각 함수들은 widget 생성, 업데이트에 사용되어 interface의 필요한 추상 메서드 작성후 사용할 필요 있다고 생각...
화면의 각 인자들을 이동하고 생성한 객체를 통해 알맞게 refresh 되는 기능 구현해보기...

2021-07-16 05:27 UTC, miking38 requested changes
수고했습니다~ 수정이 필요한부분이 보여서 코멘트 추가헀습니다.

2021-07-16 05:27 UTC, miking38 commented on app/src/main/java/com/devidea/timeleft/TimeInfoDttm.java
> +    public AdapterItem setTimeItem() {
set~ 으로 시작하는 method는 parameter로 값을 주입해서 객체의 값을 수정하는 경우에 사용되는 경우가 많습니다. 
지금은 해당 함수가 호출 되는 경우 객체 내부의 값을 업데이트만 하면 되므로 

refreshTimeItem 혹은 updateTimeItem으로 이름이 수정되는게 더 좋을것 같습니다.

2021-07-16 05:27 UTC, miking38 commented on app/src/main/java/com/devidea/timeleft/TimeInfoYear.java
> +        float YearPercent = ((float) day / 365) * 100;
이렇게 하면 윤년 처리가 안될것 같습니다. dayOfYear를 찾아보고 수정해주세요

2021-07-17 10:02 UTC, jun34724 commented on app/src/main/java/com/devidea/timeleft/TimeInfoDttm.java
> +    public AdapterItem setTimeItem() {
감사합니다. 변수명 수정해보겠습니다!

2021-07-17 10:03 UTC, jun34724 commented on app/src/main/java/com/devidea/timeleft/TimeInfoYear.java
> +        float YearPercent = ((float) day / 365) * 100;
365일 고정값이 아닌 해당 년도 일수 확인후 계산하는것으로 수정 진행하겠습니다 코드리뷰 감사합니다!!

2021-07-21 09:48 UTC, merged